### PR TITLE
remove some logs and replace others with OTP 21 logger

### LINKED ISSUE #8: Logs getting in the way
I just released a new relx and will get a new rebar3 with it out this weekend most likely.

But it only works with epmdless if the log messages are removed. This is because the relx start script does a request into the running node to return the ticktime, that way the remote console or nodetool use doesn't break due to a differing ticktime.

When epmdless was logging it would result in some log line being set to the ticktime :)

I know it is hacky but is the best we have right now. I can send a PR to remove the logs if you are ok with that. And would be good to move to the new OTP logger for any that should be kept.

### PR DESCRIPTION
**Pull request by tsloughter**
Resolves #8

### CODE REVIEW

**Comment by oltarasenko** [comment]
@tsloughter Is there a way to keep it operational for older versions of Erlang?

**Comment by tsloughter** [comment]
ah yea, if you need it to still work on older otps I can wrap the logs in a macro so it ony compiles for the new otp logger when it is avialable.

**Comment by oltarasenko** [comment]
@tsloughter yes please!

**Comment by tsloughter** [comment]
Should be good now.

**Comment by oltarasenko** [comment]
Thanks for your contribution, @tsloughter! I will close this PR, but will merge your commit as a part of https://github.com/oltarasenko/epmdless/pull/10

**Pull request closed without merging**
